# Generated by Django 4.1.3 on 2022-12-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puradata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cuit',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dni',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='professional',
            name='cuit',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='professional',
            name='dni',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
