# Generated by Django 4.1.3 on 2022-12-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puradata', '0003_alter_customer_cuit_alter_customer_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(max_length=201),
        ),
    ]
