# Generated by Django 4.1.3 on 2022-12-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puradata', '0006_remove_orderline_cash_payment_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='facturado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='cash_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='mercado_pago_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
