# Generated by Django 4.1.3 on 2022-12-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puradata', '0007_order_date_alter_order_facturado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
